/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ele: typeof import('./src/components/Ele.vue')['default']
    Element: typeof import('./src/components/Element.vue')['default']
    ElementTest: typeof import('./src/components/ElementTest.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Goods: typeof import('./src/components/goods/Goods.vue')['default']
    GoodsCatagories: typeof import('./src/components/goods/GoodsCatagories.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
