/** @type {import('cz-git').CommitizenGitOptions} */
export default {
  alias: 'fd',
  messages: {
    type: '选择本次提交的类型:',
    customType: '选择自定义提交类型:',
    subject: '简短描述（必填）:\n',
    body: '详细描述（可选，回车跳过）:\n',
    breaking: '列出任何 BREAKING CHANGES（可选，回车跳过）:\n',
    footerPrefixesSelect: '选择关联的 ISSUES 类型:',
    customFooterPrefix: '输入 ISSUES 前缀:',
    footer: '列出关联的 ISSUES (例如: #12, #45):\n',
    generatingBySquashing: '正在通过 squash 合并生成提交...',
    selectCommitType: '选择提交类型 (输入进行过滤):',
  },
  types: [
    { value: 'feat', name: 'feat:     新功能', emoji: '✨' },
    { value: 'fix', name: 'fix:      修复 bug', emoji: '🐛' },
    { value: 'docs', name: 'docs:     文档变更', emoji: '📝' },
    { value: 'style', name: 'style:    代码格式（不影响功能）', emoji: '💄' },
    { value: 'refactor', name: 'refactor: 重构（既不是新功能也不是修复）', emoji: '♻️' },
    { value: 'perf', name: 'perf:     性能优化', emoji: '⚡' },
    { value: 'test', name: 'test:     测试相关', emoji: '✅' },
    { value: 'build', name: 'build:    构建或工具变更', emoji: '📦' },
    { value: 'ci', name: 'ci:       CI 配置变更', emoji: '👷' },
    { value: 'chore', name: 'chore:    其他变更', emoji: '🔧' },
    { value: 'revert', name: 'revert:   回滚', emoji: '⏪' },
  ],
  useEmoji: true,
  themeColorCode: '',
  scopes: [
    { name: 'admin' },
    { name: 'backend' },
    { name: 'monorepo' },
    { name: 'workflows' },
    { name: 'deps' },
  ],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom',
  emptyScopesAlias: 'empty',
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  breaklineChar: '|',
  skipQuestions: ['body', 'breaking', 'footer'],
  issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: 'skip',
  customIssuePrefixAlias: 'custom',
  allowCustomIssuePrefix: true,
  allowEmptyIssuePrefix: true,
  confirmColorize: true,
  maxHeaderLength: 72,
  maxSubjectLength: 72,
  minSubjectLength: 2,
}
